### ISSUE TITLE
Add mongodb 3.2 and use as latest

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-docker-mongodb#11]

**Comment by notxarb** [comment]
Setting as latest has potential to break any existing databases if they scale.

**Comment by fabien** [comment]
Will MongoDB 3.4 be supported? How would I use this with nanobox right now?

**Comment by notxarb** [comment]
@fabien I've been working on getting 3.4 compiled. There's a linking issue that I need to figure out before the executable is ready. The next step would be to look at how it's configured. The config files have changed format since we first introduced support for MongoDB. Actually, the config file issue is one reason why we don't have support for 3.2 yet.

**Comment by fabien** [comment]
@notxarb thanks for chiming in. Version 3.4 brought some important features that I depend on, so I am definitely looking forward to that. I'm new to nanobox and it was my first concern. However, I assume it's not strictly necessary to have MongoDB working 'out of the nanobox', is it? Any 'ol MongoDB server/connection will do I guess.

**Comment by notxarb** [comment]
You do have a few options. If you don't mind managing your own MongoDB instance, then you should be able to connect to it from an app running with nanobox. I think there are places that are willing to host MongoDB for you, if you don't want to do it yourself, there's probably some added latency with that, unless they are hosting in the same datacenter. We shouldn't be blocking the app's ability to connect to resources outside of the nanobox service. Nanobox just won't be able to manage it.

**Comment by notxarb** [comment]
MongoDB 3.2.x and 3.4.x should now be available.
